%function [xPoints]=torus_phiPushCurve(aCurve,bCurve)
%This function evaluates the curve $x(t)= _torus  @  @everymath \@emptytoks  @ $
%@  ( to\@ne @size  .$ @ vec17E (t)  @  @everymath \@emptytoks  @ $ @  ) to\@ne
%@size  .$ @   R^3$ at  NPoints=31 points generated along the curve $vec17E (t)$
%using line_linspace with $ tMin=0$ and $ tMax=1$, and $a$, $b$ as given in the
%input arguments.
%INPUT: a:[2x1] theta curve parameter
%       b:[2x1] theta curve parameter
%OUTPUT:xPoints:[3xNPoints] points generated by evaluating phi_torus
function [xPoints]=torus_phiPushCurve(a,b)
NPoints = 31;
%generate point along theta(t) in t = [0,1]
[thetaPoints] = line_linspace(a,b,0,1,NPoints);
xPoints = torus_phi(thetaPoints);